version: '3.8'
services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - './postgres-volume:/var/lib/postgresql/data'
      - './csv:/csv'
      - ./init-postgre.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
#  pgadmin:
#    image: dpage/pgadmin4
#    environment:
#      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
#      - PGADMIN_DEFAULT_PASSWORD=admin
#    ports:
#      - '80:80'
#    volumes:
#      - './pgadmin:/var/lib/pgadmin'
#    depends_on:
#      - postgres
  mongodb:
    image: mongo:5.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./mongo-volume:/data/db
      - './csv:/csv'
    ports:
      - '27017:27017'
#  app:
#    depends_on:
#      - postgres
#      - mongodb