version: "3.9"

services:

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    volumes:
      - ./US_Accidents_Dec19.csv:/tmp/US_Accidents_Dec19.csv
      - ./init-import-postgres.sh:/docker-entrypoint-initdb.d/init-import-postgres.sh
    ports:
      - "5432:5432"
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=grupo7
      - POSTGRES_PASSWORD=grupo2022
      - POSTGRES_DB=accbd2

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    command: --quiet
    volumes:
      - ./US_Accidents_Dec19.csv:/tmp/US_Accidents_Dec19.csv
      - ./init-import-mongo.sh:/docker-entrypoint-initdb.d/init-import-mongo.sh
      - ./init-import-mongo02.js:/docker-entrypoint-initdb.d/init-import-mongo02.js
    ports:
      - "27017:27017"

  mongodemo:
    image: mongodemo
    container_name: mongodemo
    volumes:
      - type: bind
        source: ../mongodemo
        target: /mongodemo
    depends_on:
      - mongo
      - postgres
    ports:
      - "8080:8080"
